=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/lib/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xbrli="http://www.xbrl.org/2003/instance" elementFormDefault="qualified">
	<xs:import namespace="http://www.xbrl.org/2003/instance" schemaLocation="http://www.xbrl.org/2003/xbrl-instance-2003-12-31.xsd"/>
	<xs:attribute name="readMeFirst" type="xs:boolean" default="false"/>
	<xs:attribute name="validatorExclude" type="xs:boolean" default="false"/>
	<xs:complexType name="inputFileType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="readMeFirst" use="optional"/>
				<xs:attribute ref="validatorExclude" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="xsd" type="inputFileType"/>
	<xs:element name="linkbase" type="inputFileType"/>
	<xs:element name="instance" type="inputFileType"/>
	<xs:element name="data">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="xsd"/>
				<xs:element ref="linkbase"/>
				<xs:element ref="instance"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="result">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="expected" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="invalid"/>
								<xs:enumeration value="valid"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="variation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="data"/>
				<xs:element ref="result"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="testcase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="outpath" type="xs:string" use="required"/>
			<xs:attribute name="owner" type="xs:string" use="required"/>
			<xs:attribute name="minimal" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="instances">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="xbrli:xbrl" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/200-linkbase/212-Testcase-linkbaseDocumentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  name="linkbase (and extended link) documentation elements" 
  description="3.5.2.3 and 3.5.3.5 linkbase documentation elements." 
  outpath="out" 
  owner="geoff@galexy.net" 
  minimal="true"
  xsi:noNamespaceSchemaLocation="../lib/test.xsd" >

	<variation id="V-01" name="212-01 linkbase documentation element">
		<description>
      A valid documentation element as a child of a linkbase element.  There are no
      attributes on the documentation element.
    </description>
		<data>
			<xsd readMeFirst="true">212-01-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-01-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>

<!-- Commented out, as we don't allow schema invalid variations in the conformance suite
	<variation id="V-02" name="212-02 linkbase documentation element with an invalid attribute">
		<description>
      A documentation element as a child of a linkbase element but where the documentation
      element has an invalid attribute (missing an explicit namespace).
    </description>
		<data>
			<xsd readMeFirst="true">212-02-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-02-label.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
-->

	<variation id="V-03" name="212-03 linkbase documentation element with an xml:lang attribute">
		<description>
      A documentation element as a child of a linkbase element but where the documentation
      element has a valid xml:lang attribute.
    </description>
		<data>
			<xsd readMeFirst="true">212-03-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-03-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-04" name="212-04 linkbase documentation element with an valid attribute">
		<description>
      A documentation element as a child of a linkbase element but where the documentation
      element has a valid attribute with an explicitly declared namespace.
    </description>
		<data>
			<xsd readMeFirst="true">212-04-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-04-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-05" name="212-05 linkbase documentation element with no content">
		<description>
      A documentation element as a child of a linkbase element but where the documentation
      element has no content.
    </description>
		<data>
			<xsd readMeFirst="true">212-05-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-05-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	

	<variation id="V-06" name="212-06 extended link documentation element">
		<description>
      A valid documentation element as a child of an extended link.  There are no
      attributes on the documentation element.
    </description>
		<data>
			<xsd readMeFirst="true">212-06-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-06-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>

<!-- Commented out, as we don't allow schema invalid variations in the conformance suite
	<variation id="V-07" name="212-07 extended link documentation element with an invalid attribute">
		<description>
      A documentation element as a child of an extended link but where the documentation
      element has an invalid attribute (missing an explicit namespace).
    </description>
		<data>
			<xsd readMeFirst="true">212-07-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-07-label.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
-->

	<variation id="V-08" name="212-08 extended link documentation element with an xml:lang attribute">
		<description>
      A documentation element as a child of an extended link but where the documentation
      element has a valid xml:lang attribute.
    </description>
		<data>
			<xsd readMeFirst="true">212-08-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-08-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-09" name="212-09 extended link documentation element with a valid attribute">
		<description>
      A documentation element as a child of an extended link but where the documentation
      element has a valid attribute with an explicitly declared namespace.
    </description>
		<data>
			<xsd readMeFirst="true">212-09-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-09-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-10" name="212-10 extended link documentation element with no content">
		<description>
      A documentation element as a child of an extended link element but where the documentation
      element has no content.
    </description>
		<data>
			<xsd readMeFirst="true">212-10-schema.xsd</xsd>
			<linkbase readMeFirst="false">212-10-label.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>

</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/200-linkbase/292-Embeddedlinkbaseinthexsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Embedded Linkbases" description="Embedded linkbases" outpath="out" owner="neil.wills@ubmatrix.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">
	
	<variation id="V-00" name="292-00-Embeddedlinkbaseinthexsd.xsd">
		<description>Embedded linkbase</description>
		<data>
			<xsd readMeFirst="true">292-00-Embeddedlinkbaseinthexsd.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-01" name="292-01-Embeddedlinkbaseinthexsd.xsd">
		<description>Multiple embedded linkbases</description>
		<data>
			<xsd readMeFirst="true">292-01-Embeddedlinkbaseinthexsd.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
  <variation id="V-02" name="292-02-EmbeddedLinkbaseAndLinkbaseRef.xsd">
		<description>Multiple embedded linkbases, and a linkbaseref</description>
		<data>
			<xsd readMeFirst="true">292-02-EmbeddedLinkbaseAndLinkbaseRef.xsd</xsd>
			<xsd readMeFirst="false">201-02-LinkbaseRef.xsd</xsd>
			<linkbase readMeFirst="false">LinkbaseRef-label.xml</linkbase>
			<linkbase readMeFirst="false">LinkbaseRef-reference.xml</linkbase>
			<linkbase readMeFirst="false">LinkbaseRef-calculation.xml</linkbase>
			<linkbase readMeFirst="false">LinkbaseRef-presentation.xml</linkbase>
			<linkbase readMeFirst="false">LinkbaseRef-definition.xml</linkbase>
      
		</data>
		<result expected="valid"/>
	</variation>
	
  <variation id="V-03" name="292-03-Embeddedlinkbaseinthexsd.xsd">
		<description>Multiple embedded linkbases, the second uses invalid arcroles</description>
		<data>
			<xsd readMeFirst="true">292-03-EmbeddedLinkbaseSecondInvalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	
</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/300-instance/302-context.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Walter Hamscher (Standard Advantage) -->
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Context Segments and Scenarios" description="Section 4.4  The Context Element" outpath="out" owner="walter@hamscher.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">
	<!-- Ensure that no element descendants of segment or scenario are in the http://www.xbrl.org/2003/instance namespace. -->
	<variation id="V-01" name="SegmentValid">
		<description>302.01 Valid segment in a context</description>
		<data>
			<xsd readMeFirst="false">SegmentValid.xsd</xsd>
			<instance readMeFirst="true">302-01-SegmentValid.xml</instance>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-02" name="SegmentNamespaceInvalid">
		<description>302.02 Invalid segment in a context; contains an element defined in xbrli namespace</description>
		<data>
			<xsd readMeFirst="false">Nautilus.xsd</xsd>
			<instance readMeFirst="true">302-02-SegmentNamespaceInvalid.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-03" name="ScenarioValid">
		<description>302.03  Valid scenario in a context</description>
		<data>
			<xsd readMeFirst="false">ScenarioValid.xsd</xsd>
			<instance readMeFirst="true">302-03-ScenarioValid.xml</instance>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-04" name="ScenarioNamespaceInvalid">
		<description>302.04 Invalid scenario in a context; contains an element defined in xbrli namespace</description>
		<data>
			<xsd readMeFirst="false">Nautilus.xsd</xsd>
			<instance readMeFirst="true">302-04-ScenarioNamespaceInvalid.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Ensure that no element descendants of segment or scenario are in the XBRL element substitutionGroup. -->
	<variation id="V-05" name="SegmentSubstitutionInvalid">
		<description>302.05 Invalid segment in a context; contains an element in substitution group of xbrli:item</description>
		<data>
			<xsd readMeFirst="false">SegmentSubstitutionInvalid.xsd</xsd>
			<instance readMeFirst="true">302-05-SegmentSubstitutionInvalid.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-06" name="ScenarioSubstitutionInvalid">
		<description>302.06  Invalid scenario in a context; contains an element in substitution group of xbrli:item</description>
		<data>
			<xsd readMeFirst="false">ScenarioSubstitutionInvalid.xsd</xsd>
			<instance readMeFirst="true">302-06-ScenarioSubstitutionInvalid.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Segment and Scenario may have empty children.  -->
	<variation id="V-07" name="SegmentEmptyContent">
		<description>302.07 Segment in a context contains an element with empty content</description>
		<data>
			<xsd readMeFirst="false">SegmentEmptyContent.xsd</xsd>
			<instance readMeFirst="true">302-07-SegmentEmptyContent.xml</instance>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-08" name="ScenarioEmptyContent">
		<description>302.08 Scenario in a context contains an element with empty content</description>
		<data>
			<xsd readMeFirst="false">ScenarioEmptyContent.xsd</xsd>
			<instance readMeFirst="true">302-08-ScenarioEmptyContent.xml</instance>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- The start dateTime must precede the end dateTime.	-->
	<variation id="V-09" name="PeriodDateTimeValid">
		<description>302.09 Valid duration context with start date earlier than end date</description>
		<data>
			<xsd readMeFirst="false">ScenarioValid.xsd</xsd>
			<instance readMeFirst="true">302-09-PeriodDateTimeValid.xml</instance>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-10" name="PeriodDateTimeInvalid">
		<description>302.10 Invalid duration context with start date later than end date</description>
		<data>
			<xsd readMeFirst="false">ScenarioValid.xsd</xsd>
			<instance readMeFirst="true">302-10-PeriodDateTimeInvalid.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-11" name="DecimalAttributeOnSegmentInconsistent">
		<description>302.11 Two contexts are S-Equal even though a decimal-valued attribute in their segment elements have different lexical representations. The contexts are S-equal, so a calculation inconsistency MUST be signaled.</description>
		<data>
			<xsd>DecimalAttributeOnSegmentOrScenario.xsd</xsd>
			<instance readMeFirst="true">302-11-DecimalAttributeOnSegmentInconsistent.xbrl</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-12" name="DecimalAttributeOnScenarioInconsistent">
		<description>302.12 Two contexts are S-Equal even though a decimal-valued attribute in their scenario elements have different lexical representations. The contexts are S-equal, so a calculation inconsistency MUST be signaled.</description>
		<data>
			<xsd>DecimalAttributeOnSegmentOrScenario.xsd</xsd>
			<instance readMeFirst="true">302-12-DecimalAttributeOnScenarioInconsistent.xbrl</instance>
		</data>
		<result expected="invalid"/>
	</variation>
</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/200-linkbase/208-balance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited by Charles Hoffman, UBmatrix; CharlesHoffman@olywa.net -->
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Item-Summation Balance Constraint" description="Section 5.1.1.2 - An optional balance attribute MAY be added to the definition of an element if its type is monetaryItemType or derived from monetaryItemType. The balance attribute MUST NOT be used on items that do not have type equal to the monetaryItemType or to a type that is derived from monetaryItemType. If the idea of debit/credit balance is appropriate to the element, it MAY be indicated using this attribute." 
outpath="out" owner="charleshoffman@olywa.net" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">

	<!-- Detect violations of the constraints among the balance attribute and calculation summation item arcs 
	as documented in Table 7 of section 5.4.2 (balance.xml). -->
	<variation id="V-01" name="Item and summation have no balance attribute">
		<description>208.01 When the item and summation have no balance attribute they are consistent</description>
		<data>
			<instance readMeFirst="true">208-01-ItemNoneSummationNone-instance.xml</instance>
			<xsd readMeFirst="false">208-01-ItemNoneSummationNone.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Table 7. Constraints amoung the balance attribute and calculation arc weights

        Balance @	Balance @	CalulationArc
        From item	To item		Illegal values
        =========	=========	==============
        debit		debit		Negative (&lt; 0)
        debit		credit		Positive (&gt; 0)
        credit		debit		Positive (&gt; 0)
        credit		credit		Negative (&lt; 0)

        -->
	<!-- The eight cases should be generated programmatically to ensure coverage of weight, credit, and debit. -->
	<!-- weight = either +1 or -1 -->
	<!-- item balance = either credit or debit -->
	<!-- item balance = either credit or debit -->
	<!-- a single linkbase balance-calculation can be used, with simply two arcs, one weight +1 from A to B, one weight -1 from C to D -->
	<!-- these eight cases below written by hand -->
	<!-- Case 1 -->
	<variation id="V-02" name="Item credit, Summation credit, weight +1">
		<description>208.02 If an item is a credit, and the item it sums to is a credit, its weight MUST be +1 (greater than 0)</description>
		<data>
			<instance readMeFirst="true">208-02-ItemCreditSumCreditWeight+1-instance.xml</instance>
			<xsd readMeFirst="false">208-02-ItemCreditSumCreditWeight+1.xsd</xsd>
			<linkbase readMeFirst="false">208-02-ItemCreditSumCreditWeight+1-calculation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Case 2 -->
	<variation id="V-03" name="Item credit, Summation credit, weight -1">
		<description>208.03 If an item is a credit and the item it sums to is a credit, its weight MUST NOT be -1 (less than 0)</description>
		<data>
			<instance readMeFirst="true">208-03-ItemCreditSumCreditWeight-1-instance.xml</instance>
			<xsd readMeFirst="false">208-03-ItemCreditSumCreditWeight-1.xsd</xsd>
			<linkbase readMeFirst="false">208-03-ItemCreditSumCreditWeight-1-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Case 3 -->
	<variation id="V-04" name="Item debit, Summation credit, weight +1">
		<description>208.04 If an item is a debit, and the item it sums to is a credit, its weight MUST NOT be +1 (greater than 0)</description>
		<data>
			<instance readMeFirst="true">208-04-ItemDebitSumCreditWeight+1-instance.xml</instance>
			<xsd readMeFirst="false">208-04-ItemDebitSumCreditWeight+1.xsd</xsd>
			<linkbase readMeFirst="false">208-04-ItemDebitSumCreditWeight+1-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Case 4 -->
	<variation id="V-05" name="Item debit, Summation credit, weight -1">
		<description>208.05 If an item is a debit, and the item it sums to is a credit, its weight MUST be -1 (less than 0)</description>
		<data>
			<instance readMeFirst="true">208-05-ItemDebitSumCreditWeight-1-instance.xml</instance>
			<xsd readMeFirst="false">208-05-ItemDebitSumCreditWeight-1.xsd</xsd>
			<linkbase readMeFirst="false">208-05-ItemDebitSumCreditWeight-1-calculation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Case 5 -->
	<variation id="V-06" name="Item credit, Summation debit, weight +1">
		<description>208.06 If an item is a credit, and the item it sums to is a credit, its weight MUST NOT be +1 (greate than 0)</description>
		<data>
			<instance readMeFirst="true">208-06-ItemCreditSumDebitWeight+1-instance.xml</instance>
			<xsd readMeFirst="false">208-06-ItemCreditSumDebitWeight+1.xsd</xsd>
			<linkbase readMeFirst="false">208-06-ItemCreditSumDebitWeight+1-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Case 6 -->
	<variation id="V-07" name="Item credit, Summation debit, weight -1">
		<description>208.07 If an item is a credit, and the item it sums to is a debit, its weight MUST be -1 (less than 0)</description>
		<data>
			<instance readMeFirst="true">208-07-ItemCreditSumDebitWeight-1-instance.xml</instance>
			<xsd readMeFirst="false">208-07-ItemCreditSumDebitWeight-1.xsd</xsd>
			<linkbase readMeFirst="false">208-07-ItemCreditSumDebitWeight-1-calculation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Case 7 -->
	<variation id="V-08" name="Item debit, Summation debit, weight +1">
		<description>208.08 If an item is a debit, and the item it sums to is a debit, its weight MUST be +1 (greater than 0)</description>
		<data>
			<instance readMeFirst="true">208-08-ItemDebitSumDebitWeight+1-instance.xml</instance>
			<xsd readMeFirst="false">208-08-ItemDebitSumDebitWeight+1.xsd</xsd>
			<linkbase readMeFirst="false">208-08-ItemDebitSumDebitWeight+1-calculation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Case 8 -->
	<variation id="V-09" name="Item debit, Summation debit, weight -1">
		<description>208.09 If an item is a debit, and the item it sums to is a debit, its weight MUST NOT be -1 (less than 0)</description>
		<data>
			<instance readMeFirst="true">208-09-ItemDebitSumDebitWeight-1-instance.xml</instance>
			<xsd readMeFirst="false">208-09-ItemDebitSumDebitWeight-1.xsd</xsd>
			<linkbase readMeFirst="false">208-09-ItemDebitSumDebitWeight-1-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-10" name="Value of weight attribute must not be 0">
		<description>208.10 The value of a weight attribute MUST NOT be 0 (zero)</description>
		<data>
			<instance readMeFirst="true">208-10-WeightNotZero-instance.xml</instance>
			<xsd readMeFirst="false">208-10-WeightNotZero.xsd</xsd>
			<linkbase readMeFirst="false">208-10-WeightNotZero-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/200-linkbase/213-SummationItemArcEndpoints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited by Walter Hamscher, Standard Advantage; walter@hamscher.com -->
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2006 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Calculation Arc Endpoint Constraints" description="Section 5.2.5.2 - Summation-item arcs MUST represent relationships only between concepts that are in the item substitution group and whose type is numeric." outpath="out" owner="walter@hamscher.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">
	<!-- Case 1 -->
	<variation id="V-01" name="Summation and Item numeric">
		<description>213.01 When the Summation and Item are numeric it is consistent.</description>
		<data>
			<xsd readMeFirst="true">213-01-SummationNumeric_ItemNumeric.xsd</xsd>
			<linkbase readMeFirst="false">213-01-SummationNumeric_ItemNumeric-calculation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Case 2 -->
	<variation id="V-02" name="Summation side of arc not numeric">
		<description>213.02  The </description>
		<data>
			<xsd readMeFirst="true">213-02-SummationNonNumeric_ItemNumeric.xsd</xsd>
			<linkbase readMeFirst="false">213-02-SummationNonNumeric_ItemNumeric-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<!-- Case 3 -->
	<variation id="V-03" name="Item side of arc not numeric">
		<description>213.03</description>
		<data>
			<xsd readMeFirst="true">213-03-SummationNumeric_ItemNonNumeric.xsd</xsd>
			<linkbase readMeFirst="false">213-03-SummationNumeric_ItemNonNumeric-calculation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/200-linkbase/preferredLabel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Preferred Label" description="Section 5.2.4.2.1 The preferredLabel attribute (optional)" owner="mg@us.fujitsu.com" minimal="true" xsi:noNamespaceSchemaLocation="../lib/test.xsd" outpath="out">
	<variation id="V-1" name="pref01">
		<description>The presentationArc's 'to' concept has label resource with a role value which is equal to the value of the preferredLabel attribute.</description>
		<data>
			<xsd readMeFirst="true">prefLabel-single-language-valid.xsd</xsd>
			<linkbase readMeFirst="false">prefLabel-single-language-valid-label.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-single-language-valid-presentation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-2" name="pref02">
		<description>The presentationArc's 'to' concept does not have label resource with a role value which is equal to the value of the preferredLabel attribute.</description>
		<data>
			<xsd readMeFirst="true">prefLabel-single-language-invalid.xsd</xsd>
			<linkbase readMeFirst="false">prefLabel-single-language-invalid-label.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-single-language-invalid-presentation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-3" name="pref03">
		<description>The presentationArc's 'from' concept has label resource with a role value which is equal to the value of the preferredLabel attribute. But the presentationArc's 'to' concept does not have label resource with a role value which is equal to the value of the preferredLabel attribute. </description>
		<data>
			<xsd readMeFirst="true">prefLabel-single-language-invalid2.xsd</xsd>
			<linkbase readMeFirst="false">prefLabel-single-language-invalid2-label.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-single-language-invalid2-presentation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-4" name="pref04">
		<description>The presentationArc's 'to' concept does not have 'en' label resource with a role value which is equal to the value of the preferredLabel attribute, but has 'ja' label resource with a role value which is equal to the value of the preferredLabel attribute. </description>
		<data>
			<xsd readMeFirst="true">prefLabel-incomplete-multi-languageset.xsd</xsd>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-label.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-label-ja.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-presentation.xml</linkbase>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-5" name="pref05">
		<description> The presentationArc's 'to' concept does not have label resource with a role value which is equal to the value of the preferredLabel attribute, but the presentationArc's 'from' concept has 'ja' label resource with a role value which is equal to the value of the preferredLabel attribute.</description>
		<data>
			<xsd readMeFirst="true">prefLabel-incomplete-multi-languageset-invalid.xsd</xsd>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-invalid-label.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-invalid-label-ja.xml</linkbase>
			<linkbase readMeFirst="false">prefLabel-incomplete-multi-languageset-invalid-presentation.xml</linkbase>
		</data>
		<result expected="invalid"/>
	</variation>

</testcase>
