=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/lib/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xbrli="http://www.xbrl.org/2003/instance" elementFormDefault="qualified">
	<xs:import namespace="http://www.xbrl.org/2003/instance" schemaLocation="http://www.xbrl.org/2003/xbrl-instance-2003-12-31.xsd"/>
	<xs:attribute name="readMeFirst" type="xs:boolean" default="false"/>
	<xs:attribute name="validatorExclude" type="xs:boolean" default="false"/>
	<xs:complexType name="inputFileType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="readMeFirst" use="optional"/>
				<xs:attribute ref="validatorExclude" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="xsd" type="inputFileType"/>
	<xs:element name="linkbase" type="inputFileType"/>
	<xs:element name="instance" type="inputFileType"/>
	<xs:element name="data">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="xsd"/>
				<xs:element ref="linkbase"/>
				<xs:element ref="instance"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="result">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="expected" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="invalid"/>
								<xs:enumeration value="valid"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="variation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="data"/>
				<xs:element ref="result"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="testcase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="outpath" type="xs:string" use="required"/>
			<xs:attribute name="owner" type="xs:string" use="required"/>
			<xs:attribute name="minimal" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="instances">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="xbrli:xbrl" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/400-misc/400-nestedElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- See http://bugzilla.xbrl.org/show_bug.cgi?id=369 -->
<!-- Copyright 2003 XBRL International Inc.  See www.xbrl.org/legal.  All Rights Reserved. -->

<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Nested XBRL" description="Tests XBRL constructs nested in XML containers" outpath="out" owner="cps@descionsoft.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">

  <variation id="v01" name="400-01 single nested instance">
  	<description>Single instance nested in an XML container.</description>
  	<data>
  		<xsd readMeFirst="false">400-nestedInstanceTaxonomySchema.xsd</xsd>
  		<instance readMeFirst="true">400-01-singleNestedInstance.xml</instance>
  	</data>
  	<result expected="invalid"/>
  </variation>
  
  <variation id="v02" name="400-02 multiple nested instances">
    <description>Multiple instances nested in an XML container.</description>
    <data>
      <xsd readMeFirst="false">400-nestedInstanceTaxonomySchema.xsd</xsd>
      <instance readMeFirst="true">400-02-multipleNestedInstances.xml</instance>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v03" name="400-03 single nested schema">
    <description>Single schema nested in an XML container.</description>
    <data>
      <xsd readMeFirst="true">400-03-singleNestedSchema.xsd</xsd>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v04" name="400-04 multiple nested schemas">
    <description>Multiple schemas nested in an XML container.</description>
    <data>
      <xsd readMeFirst="true">400-04-multipleNestedSchemas.xsd</xsd>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v05" name="400-05 single nested linkbase">
    <description>Single schema nested in an XML container.</description>
    <data>
      <linkbase readMeFirst="true">400-05-singleNestedLinkbase.xsd</linkbase>
    </data>
    <result expected="invalid"/>
  </variation>
  
  <variation id="v06" name="400-06 multiple nested linkbases">
    <description>Multiple schemas nested in an XML container.</description>
    <data>
      <linkbase readMeFirst="true">400-06-multipleNestedLinkbases.xsd</linkbase>
    </data>
    <result expected="invalid"/>
  </variation>

</testcase>

=== JeffFerguson/gepsio/JeffFerguson.Gepsio.Test/XBRL-CONF-2014-12-10/Common/100-schema/161-Appinfo.xml
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International.   See www.xbrl.org/legal.  All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>

<testcase name="Appinfo"
	description="Section 3.4 
	''XBRL instances, XBRL linkbases and XBRL taxonomy schemas MUST comply with the
	syntax requirements imposed in this specification. Many of these syntax
	requirements are expressed using XML Schemas so a part of the validation
	process can be performed using XML Schema validation software.''
	
	Since annotation/appinfo stipulates lax validation, any processor that chooses
	to satisfy section 3.4 by employing a validating XML parser (such as Xerces)
	has a responsibility to ensure that the appropriate declarations for XBRL
	components are provided to that parser."
	outpath="out" owner="spec@xbrl.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/test.xsd">
	<!-- role tests -->
	<variation id="V-01" name="161-01-roleType-id-missing">
		<description>A role type declaration with a missing id. Valid, but useless.</description>
		<data>
			<xsd readMeFirst="true">161-01-roleType-id-missing-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-02" name="161-02-roleType-id-notncname">
		<description>A role type declaration with an id not an ncname. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-02-roleType-id-notncname-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-03" name="161-03-roleType-uri-missing">
		<description>A role type declaration with a missing roleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-03-roleType-uri-missing-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-04" name="161-04-roleType-uri-empty">
		<description>A role type declaration with an empty roleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-04-roleType-uri-empty-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-05" name="161-05-roleType-uri-notabsolute">
		<description>A role type declaration with roleURI not absolute. Invalid. Section
			5.1.3 -- This isn't actually invalid according to the 2008-07-02 spec; discussion required</description>
		<data>
			<xsd readMeFirst="true">161-05-roleType-uri-notabsolute-invalid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<!-- Arcrole tests -->
	<variation id="V-11" name="161-11-arcroleType-id-missing">
		<description>A arcrole type declaration with a missing id. Valid, but useless.</description>
		<data>
			<xsd readMeFirst="true">161-11-arcroleType-id-missing-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	<variation id="V-12" name="161-12-arcroleType-id-notncname">
		<description>A arcrole type declaration with an id not an ncname. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-12-arcroleType-id-notncname-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-13" name="161-13-arcroleType-uri-missing">
		<description>A arcrole type declaration with a missing arcroleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-13-arcroleType-uri-missing-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-14" name="161-14-arcroleType-uri-empty">
		<description>A arcrole type declaration with an empty arcroleURI. Invalid.</description>
		<data>
			<xsd readMeFirst="true">161-14-arcroleType-uri-empty-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-15" name="161-15-arcroleType-uri-noturi">
		<description>A arcrole type declaration with arcroleURI not absolute. Invalid. Section
			5.1.3</description>
		<data>
			<xsd readMeFirst="true">161-15-arcroleType-uri-noturi-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-16" name="161-16-arcroleType-cyclesAllowedAll">
		<description>A arcrole type declaration with cyclesAllowed = All Invalid. Section
			5.1.3</description>
		<data>
			<xsd readMeFirst="true">161-16-arcroleType-cyclesAllowedAll-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
</testcase>
